export const stories = [
  {
    idUser: "1",
    idStory: 1,
    nameStory: "Alo T8",
    image: "../../assets/images/avatar.jpg",
    imgStory: [".././src/img/story.jpg", ".././src/img/story1.jpg"],
  },
  {
    idUser: "1",
    idStory: 2,
    nameStory: "Alo T9",
    image: ".././src/img/avatar.jpg",
    imgStory: [".././src/img/story.jpg", ".././src/img/story1.jpg"],
  },
  {
    idUser: "1",
    idStory: 3,
    nameStory: "Alo T10",
    image: ".././src/img/avatar.jpg",
    imgStory: [".././src/img/story.jpg", ".././src/img/story1.jpg"],
  },
  {
    idUser: "1",
    idStory: 4,
    nameStory: "Alo T11",
    image: ".././src/img/avatar.jpg",
    imgStory: [".././src/img/story.jpg", ".././src/img/story1.jpg"],
  },
  {
    idUser: "1",
    idStory: 5,
    nameStory: "Alo T12",
    image: ".././src/img/avatar.jpg",
    imgStory: [".././src/img/story.jpg", ".././src/img/story1.jpg"],
  },
  {
    idUser: "2",
    idStory: 6,
    nameStory: "HPNY",
    image: ".././src/img/avatar.jpg",
    imgStory: [".././src/img/story.jpg", ".././src/img/story1.jpg"],
  },
  {
    idUser: "2",
    idStory: 7,
    nameStory: "Alo T1",
    image: ".././src/img/avatar.jpg",
    imgStory: [".././src/img/story.jpg", ".././src/img/story1.jpg"],
  },
  // {
  //   idUser: "1",
  //   idStory: 8,
  //   nameStory: "Alo T2",
  //   image: ".././src/img/avatar.jpg",
  //   imgStory: [".././src/img/story.jpg", ".././src/img/story1.jpg"],
  // },
  // {
  //   idUser: 1,
  //   idStory: 9,
  //   nameStory: "Alo T3",
  //   image: ".././src/img/avatar.jpg",
  //   imgStory: [".././src/img/story.jpg", ".././src/img/story1.jpg"],
  // },
  // {
  //   idUser: 1,
  //   idStory: 10,
  //   nameStory: "Alo T4",
  //   image: ".././src/img/avatar.jpg",
  //   imgStory: [".././src/img/story.jpg", ".././src/img/story1.jpg"],
  // },
],
  posts = [
    {
      idUser: "1",
      idStory: "1",
      title: "Alo T8",
      text: "Moshi moshi",
      imgPost: [".././src/img/story.jpg", ".././src/img/story1.jpg"],
      video: "",
      react: "100",
      cmt: "123",
    },
    {
      idUser: "1",
      idStory: "2",
      title: "Alo T8",
      text: "Moshi moshi",
      imgPost: [".././src/img/story.jpg", ".././src/img/story1.jpg"],
      video: "",
      react: "100",
      cmt: "123",
    },
    {
      idUser: "1",
      idStory: "3",
      title: "Alo T8",
      text: "Moshi moshi",
      imgPost: [".././src/img/story.jpg", ".././src/img/story1.jpg"],
      video: "",
      react: "100",
      cmt: "123",
    },
    {
      idUser: "1",
      idStory: "4",
      title: "Alo T8",
      text: "Moshi moshi",
      imgPost: [".././src/img/story.jpg", ".././src/img/story1.jpg"],
      video: "",
      react: "100",
      cmt: "123",
    },
    {
      idUser: "1",
      idStory: "5",
      title: "Alo T8",
      text: "Moshi moshi",
      imgPost: [".././src/img/story.jpg", ".././src/img/story1.jpg"],
      video: "",
      react: "100",
      cmt: "123",
    },
    {
      idUser: "1",
      idStory: "6",
      title: "Alo T8",
      text: "Moshi moshi",
      imgPost: [".././src/img/story.jpg", ".././src/img/story1.jpg"],
      video: "",
      react: "100",
      cmt: "123",
    },
    {
      idUser: "1",
      idStory: "7",
      title: "Alo T8",
      text: "Moshi moshi",
      imgPost: [".././src/img/story.jpg", ".././src/img/story1.jpg"],
      video: "",
      react: "100",
      cmt: "123",
    },
    {
      idUser: "2",
      idStory: "6",
      title: "Alo T8",
      text: "Moshi moshi",
      imgPost: [".././src/img/story.jpg", ".././src/img/story1.jpg"],
      video: "",
      react: "100",
      cmt: "123",
    },
    {
      idUser: "2",
      idStory: "7",
      title: "Alo T8",
      text: "Moshi moshi",
      imgPost: [".././src/img/story.jpg", ".././src/img/story1.jpg"],
      video: "",
      react: "100",
      cmt: "123",
    },
  ],
  users = [
    {
      idUser: "1",
      nameUser: "ngvinh.28",
      rName: "Gia Vinh",
      avatar: ".././src/img/avatar.jpg",
      posts: "5",
      followers: "5",
      following: "10",
      friends: ["2"]
    },
    {
      idUser: "2",
      nameUser: "vdau31.11",
      rName: "Say Dậu",
      avatar: ".././src/img/avatar.jpg",
      posts: "5",
      followers: "5",
      following: "10",
      friends: ["1"]
    },
    {
      idUser: "3",
      nameUser: "kienhoang255",
      rName: "Kien Hoang",
      avatar: ".././src/img/avatar.jpg",
      posts: "5",
      followers: "5",
      following: "10",
      friends: ["1", "2"]
    },

  ];
